---
- name: Allow access to SSH
  community.general.ufw:
    rule: allow
    port: ssh

- name: Allow access to HTTPS
  community.general.ufw:
    rule: allow
    port: https

- name: Allow access to alt. HTTPS port
  community.general.ufw:
    rule: allow
    port: '{{ https_port }}'

- name: Allow access to alt. HTTP port
  community.general.ufw:
    rule: allow
    port: '{{ http_port }}'

- name: Insert port-forwading rule in /etc/ufw/before.rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port {{ http_port }}
      -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port {{ https_port }}
      COMMIT

- name: Allow all traffic on private network
  community.general.ufw:
    rule: allow
    src: "{{ private_vpc_ip_range }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
