---
- name: Mount point /mnt/registry
  ansible.builtin.file:
    path: /mnt/registry
    state: directory
    mode: 0755

- name: Do mount volume /mnt/registry
  ansible.posix.mount:
    path: /mnt/registry
    src: LABEL={{ registry_volume_label }}
    opts: defaults,nofail,discard,noatime
    fstype: ext4
    boot: true
    state: mounted

- name: Set ownership of files in volume
  ansible.builtin.file:
    path: /mnt/registry
    state: directory
    recurse: true
    owner: worker
    group: worker

- name: Copy /auth/htpasswd
  ansible.builtin.copy:
    src: htpasswd
    dest: /home/worker/
    owner: worker
    group: worker
    mode: 0640

- name: User service dir
  ansible.builtin.file:
    path: /home/worker/.config/systemd/user
    state: directory
    owner: worker
    group: worker
    mode: 0750

- name: Copy registry service file
  ansible.builtin.template:
    src: registry.service.j2
    dest: /home/worker/.config/systemd/user/registry.service
    owner: worker
    group: worker
    mode: 0640

- name: Start & enable web service
  become: true
  become_user: worker
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: registry
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ worker_uid }}
