#!/bin/env bash

deps() {
  if ! type -p $1 &> /dev/null 
  then
      echo "'$1' must be installed to run this script."
      exit 126
  fi
}

deps "ansible-playbook"

help() {
  cat <<_EOF
    Connect to remote hosts from the ansible inventory

    usage: 
      
      remote    <command> [<arg> ...]

    commands:
      root      <host-alias>    ssh into ansible host as root

      worker    <host-alias>    ssh into ansible host as worker

      iex       <host-alias>    start iex prompt at host 

      migrate   <host-alias>    run db migrations on host

      help                     print help
_EOF
}

(( $# < 1 )) && {
    help
    exit 126
}

function ansible_host_ip() {
  cd ansible && ansible-inventory --host $1 | jq -r '.ansible_host'
}

case "$1" in
    root)
        (( $# < 2 )) && {
            help
            exit 126
        }
        IFS='@'
        HOST=$2
        IP="$(ansible_host_ip $HOST)"
        ssh root@$IP
        ;;
    worker)
        (( $# < 2 )) && {
            help
            exit 126
        }
        IFS='@'
        HOST=$2
        IP="$(ansible_host_ip $HOST)"
        ssh root@$IP -t "su - worker"
        ;;
    iex)
        (( $# < 2 )) && {
            help
            exit 126
        }
        HOST=$2
        IP="$(ansible_host_ip $HOST)"
        ssh root@$IP -t "su - worker bash -c './ectl iex'"
        ;;
    migrate)
        (( $# < 2 )) && {
            help
            exit 126
        }
        HOST=$2
        IP="$(ansible_host_ip $HOST)"
        ssh root@$IP -t "su - worker bash -c './ectl migrate'"
        ;;
    help)
        help
        ;;
    *)
        help
        exit 126
        ;;
esac

