---
- name: User service dir
  ansible.builtin.file:
    path: /home/worker/.config/systemd/user
    state: directory
    owner: worker
    group: worker
    mode: 0750

- name: Copy builder service file
  ansible.builtin.template:
    src: builder.service.j2
    dest: /home/worker/.config/systemd/user/builder.service
    owner: worker
    group: worker
    mode: 0640

- name: Start & enable builder service
  become: true
  become_user: worker
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: builder
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ worker_uid }}

- name: Migrate builder database
  become: true
  become_user: worker
  changed_when: false
  ansible.builtin.command: /home/worker/ectl migrate
