---
- name: Allow access to SSH
  community.general.ufw:
    rule: allow
    port: ssh

- name: Allow access to port 4430
  community.general.ufw:
    rule: allow
    port: 4430

- name: Allow access to port 8000
  community.general.ufw:
    rule: allow
    port: 8000

- name: Insert port-forwading rule in /etc/ufw/before.rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8000
      -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 4430
      COMMIT

- name: Allow all traffic on private network
  community.general.ufw:
    rule: allow
    src: "{{ private_vpc_ip_range }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
