---
- name: Create container group
  ansible.builtin.group:
    name: container
    gid: "{{ container_uid }}"
    state: present

- name: Create worker group
  ansible.builtin.group:
    name: worker
    gid: "{{ worker_uid }}"
    state: present

- name: Create user container
  ansible.builtin.user:
    name: container
    uid: "{{ container_uid }}"
    shell: /bin/false
    home: /dev/null
    groups:
      - container
    password: "!"

- name: Create user worker
  ansible.builtin.user:
    name: worker
    uid: "{{ worker_uid }}"
    shell: /bin/bash
    groups:
      - worker
      - container
    password: "!"

- name: Loginctl enable-linger worker
  changed_when: false
  ansible.builtin.command: loginctl enable-linger worker
