---
- name: Add AllowUsers to /etc/ssh/sshd_config
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    block: |
      AllowUsers root worker@{{ private_vpc_ip_range }}

- name: /home/worker/.ssh
  ansible.builtin.file:
    path: /home/worker/.ssh
    state: directory
    owner: worker
    group: worker
    mode: 0500

- name: Copy /home/worker/.ssh/id_ed25519
  ansible.builtin.copy:
    src: id_ed25519-worker
    dest: /home/worker/.ssh/id_ed25519
    owner: worker
    group: worker
    mode: 0400

- name: Copy /home/worker/.ssh/id_ed25519.pub
  ansible.builtin.copy:
    src: id_ed25519-worker.pub
    dest: /home/worker/.ssh/id_ed25519.pub
    owner: worker
    group: worker
    mode: 0400

- name: Copy /home/worker/.ssh/authorized_keys
  ansible.builtin.copy:
    src: id_ed25519-worker.pub
    dest: /home/worker/.ssh/authorized_keys
    owner: worker
    group: worker
    mode: 0600
