#!/bin/env bash

deps() {
  if ! type -p $1 &> /dev/null 
  then
      echo "'$1' must be installed to run this script."
      exit 126
  fi
}

deps "podman"

help() {
  cat <<_EOF
    Connect to elixir release running inside container

    usage: 
      
      ectl    <command>   [<arg> ...]

    commands:

      iex         start a remote prompt
      
      migrate     run migrations

      seed        seed database

      help        print help
_EOF
}

(( $# < 1 )) && {
    help
    exit 126
}

case "$1" in
    iex)
        podman exec -it service bin/app remote
        ;;
    migrate)
        podman exec -it service bin/migrate
        ;;
    seed)
        podman exec -it service bin/seed
        ;;
    help)
        help
        ;;
    *)
        help
        exit 126
        ;;
esac
