#!/bin/env bash

deps() {
  if ! type -p $1 &> /dev/null 
  then
      echo "'$1' must be installed to run this script."
      exit 126
  fi
}

deps "podman"

help() {
  cat <<_EOF
    Connect to elixir release running inside container

    usage: 
      
      ectl <command> [<arg> ...]

    commands:

      iex         start a remote iex prompt

      help        print help
_EOF
}

(( $# < 1 )) && {
    help
    exit 126
}

case "$1" in
    remote)
        podman exec -it service bin/tell remote
        ;;
    help)
        help
        ;;
    *)
        help
        exit 126
        ;;
esac
