---
- name: User service dir
  ansible.builtin.file:
    path: /home/worker/.config/systemd/user
    state: directory
    owner: worker
    group: worker
    mode: 0700

- name: Copy continue service file
  ansible.builtin.template:
    src: continue.service.j2
    dest: /home/worker/.config/systemd/user/continue.service
    owner: worker
    group: worker
    mode: 0400

- name: Start & enable continue service
  become: true
  become_user: worker
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: continue
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ worker_uid }}

- name: Migrate continue database
  become: true
  become_user: worker
  changed_when: false
  ansible.builtin.command: /home/worker/ectl migrate
