---
- name: User service dir
  file: 
    path: /home/worker/.config/systemd/user
    state: directory
    owner: worker
    group: worker

- name: Copy builder service file
  template:
    src: builder.service.j2
    dest: /home/worker/.config/systemd/user/builder.service
    owner: worker
    group: worker

- name: Start & enable builder service
  become: true
  become_user: worker
  systemd:
    daemon_reload: true
    enabled: true
    name: builder
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: '/run/user/{{ worker_uid }}'

- name: Migrate database
  become: true
  become_user: worker
  command: /home/worker/ectl migrate
