#!/bin/env bash
#!/bin/env bash

deps() {
  if ! type -p $1 &> /dev/null 
  then
      echo "'$1' must be installed to run this script."
      exit 126
  fi
}

deps "podman"

help() {
  cat <<_EOF
    example script

    usage: 
      
      create-htpasswd <username> <password>
_EOF
}

(( $# < 2 )) && {
    help
    exit 126
}

podman run --entrypoint htpasswd httpd:2 -Bbn $1 $2 > htpasswd
