---
- name: Install common
  hosts: continue registry web
  remote_user: root
  roles:
    - common_packages
    - common_users
    - common_files
    - common_ssh

- name: Install registry service
  hosts: registry
  remote_user: root
  roles:
    - registry_firewall
    - registry_service

- name: Install continue services
  hosts: continue
  remote_user: root
  roles:
    - continue_firewall
    - continue_service

- name: Install web services
  hosts: web
  remote_user: root
  roles:
    - web_firewall
    - web_service
