---
- name: Install registry service
  hosts: registry
  remote_user: root
  roles:
    - common_packages
    - common_users
    - common_files
    - firewall
    - ssh
    - registry_service

- name: Install other services
  hosts: builder web
  remote_user: root
  roles:
    - common_packages
    - common_users
    - common_files
    - firewall
    - ssh

- name: Install builder service
  hosts: builder
  remote_user: root
  roles:
    - builder_service

- name: Install web service
  hosts: web
  remote_user: root
  roles:
    - web_service
