---
- name: Update containers
  hosts: web builder
  remote_user: root

  roles:
    - pull_latest

- name: Migrate builder database
  hosts: builder
  remote_user: root
  become: true
  become_user: worker

  tasks:
    - name: Migrate builder_prod
      ansible.builtin.command: /home/worker/ectl migrate
