---
- name: Update containers
  hosts: web continue
  remote_user: root

  roles:
    - pull_latest

- name: Migrate continue database
  hosts: continue
  remote_user: root
  become: true
  become_user: worker

  tasks:
    - name: Migrate continue_prod
      ansible.builtin.command: /home/worker/ectl migrate
