---
- name: Renew registry service
  hosts: registry
  remote_user: root
  roles:
    - registry_service

- name: Renew builder service
  hosts: builder
  remote_user: root
  roles:
    - builder_service

- name: Renew web service
  hosts: web
  remote_user: root
  roles:
    - web_service
