---
- name: Update containers
  hosts: web builder
  remote_user: root

  roles:
    - update-containers

- name: Migrate databases
  hosts: builder
  remote_user: root
  become: true
  become_user: worker

  tasks:
    - name: Migrate builder_prod
      command: /home/worker/ectl migrate

