---
- name: Copy /root/.docker/config.json
  ansible.builtin.copy:
    src: config.json
    dest: /root/.docker/
    mode: 0640

- name: Copy /home/worker/.docker/config.json
  ansible.builtin.copy:
    src: config.json
    dest: /home/worker/.docker/
    owner: worker
    group: worker
    mode: 0440

- name: Copy /cert/fullchain.pem
  ansible.builtin.copy:
    src: fullchain.pem
    dest: /cert/
    owner: worker
    group: container
    mode: 0440

- name: Copy /cert/privkey.pem
  ansible.builtin.copy:
    src: privkey.pem
    dest: /cert/
    owner: worker
    group: container
    mode: 0440

- name: /cert permissions
  ansible.builtin.file:
    path: /cert
    state: directory
    mode: 0755

- name: Copy /etc/sysctl.d/999-ports.conf
  ansible.builtin.copy:
    src: 999-ports.conf
    dest: /etc/sysctl.d/
    mode: 0644

- name: Reboot (999-ports.conf)
  ansible.builtin.reboot:
  when: not skip_reboot
