---
- name: Copy /root/.docker/config.json
  ansible.builtin.copy:
    src: config.json
    dest: /root/.docker/
    mode: 0400

- name: Copy /home/worker/.docker/config.json
  ansible.builtin.copy:
    src: config.json
    dest: /home/worker/.docker/
    owner: worker
    group: container
    mode: 0440

- name: Copy /cert/fullchain.pem
  ansible.builtin.copy:
    src: fullchain.pem
    dest: /home/worker/cert/
    owner: worker
    group: container
    mode: 0440

- name: Copy /cert/privkey.pem
  ansible.builtin.copy:
    src: privkey.pem
    dest: /home/worker/cert/
    owner: worker
    group: container
    mode: 0440

- name: /cert permissions
  ansible.builtin.file:
    path: /home/worker/cert
    state: directory
    mode: 0550

- name: Copy script ectl
  ansible.builtin.copy:
    src: ectl
    dest: /home/worker/
    owner: worker
    group: worker
    mode: 0700
